package com.example.utils

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.widget.Toast
import com.example.data.database.PrayerNotificationLog
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object WhatsAppExporter {

    private val dateFormat = SimpleDateFormat("EEEE, dd MMMM yyyy", Locale("id", "ID"))
    private val timeFormat = SimpleDateFormat("HH:mm:ss", Locale("id", "ID"))

    /**
     * Formats a single prayer notification log as a WhatsApp message
     */
    fun formatSingleLog(log: PrayerNotificationLog): String {
        val dateStr = dateFormat.format(Date(log.timestamp))
        val loggedTimeStr = timeFormat.format(Date(log.timestamp))
        val statusEmoji = if (log.isPreReminder) "⏳" else "🕌"
        val statusText = if (log.isPreReminder) "Pengingat 10 Menit Sebelum Waktu" else "Telah Masuk Waktu Sholat"

        val sb = StringBuilder()
        sb.appendLine("🕌 *ZUCCHERO WAKTU SHOLAT AI*")
        sb.appendLine("━━━━━━━━━━━━━━━━━━━")
        sb.appendLine("$statusEmoji *Status:* $statusText")
        sb.appendLine("⏰ *Waktu Sholat:* ${log.prayerName} (${log.prayerTime} WIB)")
        sb.appendLine("📅 *Tanggal:* $dateStr")
        sb.appendLine("⏱️ *Waktu Dicatat:* $loggedTimeStr WIB")
        if (log.locationName.isNotEmpty()) {
            sb.appendLine("📍 *Lokasi:* ${log.locationName}")
        }
        sb.appendLine("💬 *Pesan:* ${log.message}")
        sb.appendLine("━━━━━━━━━━━━━━━━━━━")
        sb.appendLine("🤲 _\"Sesungguhnya shalat itu adalah fardhu yang ditentukan waktunya atas orang-orang yang beriman.\" (QS. An-Nisa: 103)_")
        sb.appendLine("")
        sb.appendLine("✨ *Dikirim melalui ZUCCHERO Waktu Sholat AI*")
        return sb.toString().trim()
    }

    /**
     * Formats multiple prayer notification logs as a formatted WhatsApp report
     */
    fun formatMultipleLogs(logs: List<PrayerNotificationLog>, locationName: String = ""): String {
        if (logs.isEmpty()) {
            return "🕌 *ZUCCHERO WAKTU SHOLAT AI*\nBelum ada riwayat notifikasi sholat yang tercatat."
        }

        val todayDate = dateFormat.format(Date())
        val sb = StringBuilder()
        sb.appendLine("🕌 *LAPORAN RIWAYAT NOTIFIKASI WAKTU SHOLAT*")
        sb.appendLine("*ZUCCHERO Waktu Sholat AI*")
        sb.appendLine("━━━━━━━━━━━━━━━━━━━")
        sb.appendLine("📅 *Tanggal Laporan:* $todayDate")
        if (locationName.isNotEmpty()) {
            sb.appendLine("📍 *Lokasi:* $locationName")
        }
        sb.appendLine("📊 *Total Riwayat:* ${logs.size} notifikasi")
        sb.appendLine("━━━━━━━━━━━━━━━━━━━")
        sb.appendLine("📋 *Daftar Riwayat:*")

        logs.forEachIndexed { index, log ->
            val logTime = timeFormat.format(Date(log.timestamp))
            val tag = if (log.isPreReminder) "⏳ Pengingat (-10m)" else "✅ Masuk Waktu"
            sb.appendLine("${index + 1}. *${log.prayerName}* (${log.prayerTime} WIB)")
            sb.appendLine("    • Status: $tag")
            sb.appendLine("    • Waktu Alarm: $logTime")
            if (log.locationName.isNotEmpty()) {
                sb.appendLine("    • Lokasi: ${log.locationName}")
            }
        }

        sb.appendLine("━━━━━━━━━━━━━━━━━━━")
        sb.appendLine("🤲 _\"Dan dirikanlah sholat, tunaikanlah zakat dan ruku'lah beserta orang-orang yang ruku'.\" (QS. Al-Baqarah: 43)_")
        sb.appendLine("")
        sb.appendLine("✨ *Generated by ZUCCHERO Waktu Sholat AI*")
        return sb.toString().trim()
    }

    /**
     * Shares formatted text directly to WhatsApp or launches chooser
     */
    fun shareToWhatsApp(context: Context, formattedText: String) {
        try {
            val waIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                `package` = "com.whatsapp"
                putExtra(Intent.EXTRA_TEXT, formattedText)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(waIntent)
        } catch (e: Exception) {
            // WhatsApp not installed, fallback to generic sharing chooser
            try {
                val shareIntent = Intent(Intent.ACTION_SEND).apply {
                    type = "text/plain"
                    putExtra(Intent.EXTRA_TEXT, formattedText)
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                val chooser = Intent.createChooser(shareIntent, "Kirim via WhatsApp / Bagikan").apply {
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                context.startActivity(chooser)
            } catch (ex: Exception) {
                Toast.makeText(context, "Gagal membagikan pesan: ${ex.message}", Toast.LENGTH_SHORT).show()
            }
        }
    }

    /**
     * Copies the text to device clipboard
     */
    fun copyToClipboard(context: Context, text: String, label: String = "Log Waktu Sholat") {
        try {
            val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
            val clip = ClipData.newPlainText(label, text)
            clipboard.setPrimaryClip(clip)
            Toast.makeText(context, "Pesan WhatsApp berhasil disalin ke clipboard! 📋", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            Toast.makeText(context, "Gagal menyalin teks: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }
}
